# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casadopia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_domicilio', models.IntegerField(choices=[('1', 'Casa'), ('2', 'Apartamento'), ('3', 'Sobrado')], default='1')),
                ('tipo_propriedade', models.IntegerField(choices=[('1', 'Pr\xf3pria'), ('2', 'Alugada'), ('3', 'Emprestada')], default='1')),
                ('tipo_edificacao', models.IntegerField(choices=[('1', 'Alvenaria'), ('2', 'Madeira'), ('3', 'H\xedbrido')], default='1')),
                ('nro_comodos', models.IntegerField()),
                ('nro_dormitorios', models.IntegerField()),
                ('agua_encanada', models.IntegerField(choices=[('1', 'Individual'), ('2', 'Coletivo'), ('3', 'N\xe3o tem')], default='1')),
                ('luz_eletrica', models.IntegerField(choices=[('1', 'Individual'), ('2', 'Coletivo'), ('3', 'N\xe3o tem')], default='1')),
                ('gas_encanado', models.IntegerField(choices=[('1', 'Individual'), ('2', 'Coletivo'), ('3', 'N\xe3o tem')], default='1')),
            ],
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='habitacao',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casadopia.Endereco'),
        ),
    ]
