# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 00:35
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('casadopia', '0002_auto_20180303_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('cpf', models.IntegerField()),
                ('rg', models.IntegerField()),
                ('data_nascimento', models.DateField()),
                ('telefone_primario', models.IntegerField()),
                ('telefone_secundario', models.IntegerField()),
                ('genero', models.IntegerField(choices=[('1', 'Masculino'), ('2', 'Feminino'), ('3', 'Transg\xeanero')])),
                ('turno', models.IntegerField(choices=[('1', 'Matutino'), ('2', 'Vespertino')])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 3, 9, 0, 34, 1, 56000, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Atendido',
                'verbose_name_plural': 'Atendidos',
            },
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.IntegerField(choices=[('1', 'Matutino'), ('2', 'Vespertino')])),
                ('serie', models.IntegerField(choices=[('1', '1\xba'), ('2', '2\xba'), ('3', '3\xba'), ('4', '4\xba'), ('5', '5\xba'), ('6', '6\xba'), ('7', '7\xba'), ('8', '8\xba'), ('9', '9\xba')])),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)])),
                ('reprovou', models.BooleanField(default=False)),
                ('observacao', models.TextField()),
                ('atendido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casadopia.Atendido')),
            ],
            options={
                'verbose_name': 'Escolaridade',
                'verbose_name_plural': 'Escolaridade',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis_familiar', models.IntegerField()),
                ('cras_referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('bolsa_familia', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 3, 9, 0, 34, 1, 50000, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fam\xedlia',
                'verbose_name_plural': 'Fam\xedlias',
            },
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('cpf', models.IntegerField(blank=True, null=True)),
                ('idade', models.IntegerField()),
                ('estado_civil', models.IntegerField(blank=True, choices=[('1', 'Solteiro'), ('2', 'Casado'), ('3', 'Uni\xe3o Est\xe1vel'), ('4', 'Vi\xfavo')], null=True)),
                ('escolaridade', models.IntegerField(choices=[('1', 'Fundamental - Incompleto'), ('2', 'Fundamental - Completo'), ('3', 'M\xe9dio - Incompleto'), ('4', 'M\xe9dio - Completo'), ('5', 'Superior - Incompleto'), ('6', 'Superior - Completo'), ('7', 'P\xf3s-gradua\xe7\xe3o (Lato senso) - Incompleto'), ('8', 'P\xf3s-gradua\xe7\xe3o (Lato senso) - Completo'), ('9', 'P\xf3s-gradua\xe7\xe3o (Stricto sensu, n\xedvel mestrado) - Incompleto'), ('10', 'P\xf3s-gradua\xe7\xe3o (Stricto sensu, n\xedvel mestrado) - Completo'), ('11', 'P\xf3s-gradua\xe7\xe3o (Stricto sensu, n\xedvel doutor) - Incompleto'), ('12', 'P\xf3s-gradua\xe7\xe3o (Stricto sensu, n\xedvel doutor) - Completo')])),
                ('genero', models.IntegerField(choices=[('1', 'Masculino'), ('2', 'Feminino'), ('3', 'Transg\xeanero')])),
                ('profissao', models.CharField(max_length=255)),
                ('renda_mensal', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 3, 9, 0, 34, 1, 54000, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
            },
        ),
        migrations.CreateModel(
            name='GrauParentesco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel_legal', models.BooleanField(default=False)),
                ('contato', models.BooleanField(default=False)),
                ('grau', models.IntegerField(choices=[('1', 'Pai'), ('2', 'M\xe3e'), ('3', 'Padrasto'), ('4', 'Madrasta'), ('5', 'Irm\xe3o'), ('6', 'Av\xf4'), ('7', 'Tio'), ('8', 'Sobrinho'), ('9', 'Bisav\xf4'), ('10', 'Primo'), ('11', 'Cunhado')])),
                ('atendido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casadopia.Atendido')),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casadopia.Familiar')),
            ],
            options={
                'verbose_name': 'Grau de Parentesco',
                'verbose_name_plural': 'Graus de Paretesco',
            },
        ),
        migrations.CreateModel(
            name='HistoricoSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[('1', 'Diagn\xf3stico f\xedsico'), ('2', 'Diagn\xf3stico mental'), ('3', 'Acompanhamento profissional'), ('4', 'Uso continuo de medicamentos'), ('5', 'Alergias')])),
                ('descricao', models.TextField()),
                ('atendido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casadopia.Atendido')),
            ],
            options={
                'verbose_name': 'Hist\xf3rico de Sa\xfade',
                'verbose_name_plural': 'Hist\xf3rico de Sa\xfade',
            },
        ),
        migrations.CreateModel(
            name='InstituicaoExterna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 3, 9, 0, 34, 1, 49000, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institui\xe7\xe3o Externa',
                'verbose_name_plural': 'Institui\xe7\xf5es Externas',
            },
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endere\xe7o', 'verbose_name_plural': 'Endere\xe7os'},
        ),
        migrations.AlterModelOptions(
            name='habitacao',
            options={'verbose_name': 'Habita\xe7\xe3o', 'verbose_name_plural': 'Habita\xe7\xf5es'},
        ),
        migrations.AddField(
            model_name='endereco',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 0, 34, 1, 48000, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='endereco',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='habitacao',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 0, 34, 1, 52000, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='habitacao',
            name='rede_esgoto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='habitacao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='habitacao',
            name='endereco',
            field=models.ForeignKey(default=2016, on_delete=django.db.models.deletion.CASCADE, to='casadopia.Endereco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instituicaoexterna',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casadopia.Endereco'),
        ),
        migrations.AddField(
            model_name='familiar',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casadopia.Endereco'),
        ),
        migrations.AddField(
            model_name='familiar',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casadopia.Familia'),
        ),
        migrations.AddField(
            model_name='familia',
            name='auxilio_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casadopia.InstituicaoExterna'),
        ),
        migrations.AddField(
            model_name='escolaridade',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casadopia.InstituicaoExterna'),
        ),
        migrations.AddField(
            model_name='atendido',
            name='encaminhamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casadopia.InstituicaoExterna'),
        ),
        migrations.AddField(
            model_name='atendido',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casadopia.Familia'),
        ),
        migrations.AddField(
            model_name='habitacao',
            name='familia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='casadopia.Familia'),
            preserve_default=False,
        ),
    ]
